[tool.black]
line-length = 79

[tool.isort]
profile = "black"

[tool.pylint.messages_control]
disable = ["import-error"]

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"